// The mock provider adapter.
//
// Not a test hack — Architecture §5 planned for a local-dev provider from the
// start, and it earns its place three ways:
//
//   1. the E2E suite must stay green without depending on a third party's
//      uptime (which, as Phase 4 discovered on day one, is not a hypothetical);
//   2. the retry-on-malformed and seeded-fallback paths (Rule 9) are otherwise
//      only reachable by getting lucky with a bad generation — AI_MOCK_MODE makes
//      them reachable on demand, which is what lets the QA matrix actually test
//      them instead of asserting they exist;
//   3. it keeps the app fully usable with AI switched off.
//
// It reports ESTIMATED token counts (chars/4) for the text it really handled, and
// lib/ai/config.ts prices the "mock" model at zero. So the /usage readout shows
// truthful call and token volume while never inventing a dollar of spend.

import type { Provider, ProviderResponse } from "../types";

/**
 * Failure injection for QA. Set AI_MOCK_MODE in .env.local:
 *   ok            — always returns schema-valid JSON (default)
 *   malformed     — always returns junk → retry, then the caller's seeded fallback
 *   malformed-once— first dispatch junk, second valid → proves the RETRY recovers
 *   error         — throws, as a provider outage does
 */
type MockMode = "ok" | "malformed" | "malformed-once" | "error";

function mode(): MockMode {
  const m = process.env.AI_MOCK_MODE;
  if (m === "malformed" || m === "malformed-once" || m === "error") return m;
  return "ok";
}

/** Rough but honest: ~4 chars per token. Labelled an estimate wherever it surfaces. */
function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

function firstMatch(text: string, re: RegExp, fallback: string): string {
  const m = text.match(re);
  return m?.[1]?.trim() || fallback;
}

function buildRoadmap(input: string): unknown {
  const weeks = Number(firstMatch(input, /WEEKS:\s*(\d+)/, "5")) || 5;
  const track = firstMatch(input, /ROLE:\s*(.+)/, "Frontend track");
  return {
    title: `${track} — mock plan`,
    subtitle: `Generated by the mock provider · ${weeks} weeks`,
    weeks: Array.from({ length: weeks }, (_, i) => ({
      title: `Mock week ${i + 1}`,
      killCriterion: `Explain and implement week ${i + 1}'s core idea cold, with no notes and no reference.`,
      topics: [`Mock topic ${i + 1}A`, `Mock topic ${i + 1}B`, `Mock topic ${i + 1}C`],
    })),
  };
}

function buildTopicDetail(input: string): unknown {
  const topic = firstMatch(input, /TOPIC:\s*(.+)/, "the topic");
  return {
    model: `Mock mental model for ${topic}: state the single sentence you would lead with in an interview, then justify it with one mechanism and one consequence.`,
    resources: [
      { title: `Mock primary reference for ${topic}`, meta: "docs · 20 min", tag: "Docs" },
      { title: `Mock deep dive on ${topic}`, meta: "article · 35 min", tag: "Deep" },
    ],
    exercises: [
      { title: "Explain it cold", desc: `Say what ${topic} is in 90 seconds with no notes.` },
      { title: "Build the smallest case", desc: `Implement a minimal ${topic} example, then break one assumption.` },
    ],
  };
}

function buildRecall(input: string): unknown {
  const topic = firstMatch(input, /TOPIC:\s*(.+)/, "the topic");
  return {
    questions: [
      `What is the single mechanism that makes ${topic} behave the way it does, and what breaks if it is absent?`,
      `Name a concrete case where ${topic} is the wrong tool, and say what you would reach for instead.`,
      `Walk through ${topic} end to end from memory, naming the step most people skip.`,
    ],
  };
}

export function createMockProvider(): Provider {
  let dispatches = 0;

  return {
    name: "mock",

    async complete({ system, input, jsonSchema }): Promise<ProviderResponse> {
      dispatches += 1;
      const m = mode();

      if (m === "error") throw new Error("mock provider: simulated outage");

      // Which generation is this? Detected from the schema's own shape rather
      // than a passed-in flag, so the mock can't drift out of sync with what the
      // caller actually asked for.
      const props = jsonSchema?.properties ?? {};
      const payload = props.weeks
        ? buildRoadmap(input)
        : props.questions
          ? buildRecall(input)
          : buildTopicDetail(input);

      const malformed =
        m === "malformed" || (m === "malformed-once" && dispatches === 1);

      // Not just invalid JSON — JSON that PARSES but fails schema validation.
      // That is the realistic failure (a model returning a plausible-looking
      // object with a missing field), and the one a JSON.parse check alone
      // would wave straight through into the database.
      const text = malformed
        ? JSON.stringify({ title: "", weeks: [], oops: "schema-invalid on purpose" })
        : JSON.stringify(payload);

      return {
        text,
        usage: {
          inputTokens: estimateTokens(system + input),
          outputTokens: estimateTokens(text),
          // Never fabricated. The mock has no cache, so the honest number is 0 —
          // which is why cache hit-rate is only meaningful against a live provider.
          cachedInputTokens: 0,
        },
      };
    },
  };
}
